### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Zaldaryon** [ApacheTech-VintageStory-Mods/Knapster#3]
**Describe the Bug:**
I was knapping with the auto complete tool te fire brick recipe added by a mod. I never had an issue with it until today. Knapster 2.6.1 in a 1.18.15 mp server (Aura Fury Symphony).

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.GameContent.ItemClay.SetToolMode(ItemSlot slot, IPlayer byPlayer, BlockSelection blockSel, Int32 toolMode) in VSSurvivalMod\Item\ItemClay.cs:line 1516
   at ApacheTech.VintageMods.Knapster.Features.EasyClayForming.Patches.EasyClayFormingUniversalPatches.UniversalPatch_BlockEntityClayForm_OnUseOver_Prefix(BlockEntityClayForm __instance, IPlayer byPlayer, Boolean mouseBreakMode, Vec3i voxelPos, BlockFacing facing, ItemStack& ___workItemStack)
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver_Patch1(BlockEntityClayForm this, IPlayer byPlayer, Vec3i voxelPos, BlockFacing facing, Boolean mouseBreakMode)
   at Vintagestory.GameContent.BlockEntityClayForm.OnUseOver(IPlayer byPlayer, Int32 selectionBoxIndex, BlockFacing facing, Boolean mouseBreakMode) in VSSurvivalMod\BlockEntity\BEClayForm.cs:line 153
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.HandleHandInteraction(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 332
   at Vintagestory.Client.NoObf.SystemMouseInWorldInteractions.OnGameTick(Single dt) in VintagestoryLib\Client\Systems\Player\MouseInWorldInteractions.cs:line 165
   at Vintagestory.Common.EventManager.TriggerGameTick(Int64 ellapsedMilliseconds, IWorldAccessor world) in VintagestoryLib\Common\EventManager.cs:line 59
   at Vintagestory.Client.NoObf.ClientMain.MainRenderLoop(Single dt) in VintagestoryLib\Client\ClientMain.cs:line 796
   at Vintagestory.Client.NoObf.ClientMain.MainGameLoop(Single deltaTime) in VintagestoryLib\Client\ClientMain.cs:line 712
   at Vintagestory.Client.GuiScreenRunningGame.RenderToPrimary(Single dt) in VintagestoryLib\Client\MainMenu\Screens\GuiScreenRunningGame.cs:line 200
   at Vintagestory.Client.ScreenManager.Render(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 668
   at Vintagestory.Client.ScreenManager.OnNewFrame(Single dt) in VintagestoryLib\Client\ScreenManager.cs:line 643
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(FrameEventArgs e) in VintagestoryLib\Client\ClientPlatform\GameWindow.cs:line 77
   at OpenTK.Windowing.Desktop.GameWindow.Run()
   at Vintagestory.Client.ClientProgram.Start(ClientProgramArgs args, String[] rawArgs) in VintagestoryLib\Client\ClientProgram.cs:line 313
   at Vintagestory.Client.ClientProgram.<>c__DisplayClass9_0.<.ctor>b__1() in VintagestoryLib\Client\ClientProgram.cs:line 129
   at Vintagestory.ClientNative.CrashReporter.Start(ThreadStart start) in VintagestoryLib\Client\ClientPlatform\ClientNative\CrashReporter.cs:line 93
```

**Comment by ApacheTech** [comment]
By knapping, do you mean ClayForming?

**Comment by ApacheTech** [comment]
**DEV NOTE:**

https://github.com/ApacheTech-VintageStory-Mods/Knapster/blob/master/src/Knapster/Features/EasyClayForming/Patches/EasyClayFormingUniversalPatches.cs#L34

Early return `true` if any inputs, or `toolMode` is null.

**Comment by Zaldaryon** [comment]
> By knapping, do you mean ClayForming?

Ah yes, sorry, I forgot to mention. I was clayforming fireclay bricks with the auto complete function by the Knapster mod.
